---
title: "Page non trouvée"
---

<link href="styles.css" rel="stylesheet">

La page que vous cherchez est introuvable sur ce site.

<div class="scene">
  <div class="digit left">4</div>
  <div class="digit center">0</div>
  <div class="digit right">4</div>
  <div class="sep"></div>
  <div class="squish left"></div>
  <div class="squish center"></div>
  <div class="squish right"></div>
</div>

<br/><br/>



<style>
.scene {
  text-align: center;
  color: var(--bs-body-color);
}

.sep {
  border: 0pt solid var(--bs-body-color);
  border-bottom-width: 10pt;
  font-size: 100pt;
  height: 0pt;
  margin-top: 59pt;
  z-index: 10;
}

.digit {
  display: inline-block;
  color: var(--bs-body-color);
  font-family: monospace;
  font-size: 100pt;
  border: 0pt solid black;
}

.digit.left, .digit.center, .digit.right {
  animation-name: bounce;
  animation-duration: none;
  animation-direction: normal;
  animation-iteration-count: infinite;
  animation-timing-function: normal;
}



.squish {
  display: inline-block;
  border-radius: 100%;
  background-color: var(--bs-body-color);
  font-size: 100pt;
  font-family: monospace;
  width: 40pt;
  height: 40pt;
  margin-left: 5pt;
  margin-right: 5pt;

  z-index: 0;

  animation-name: squish;
  animation-duration: none;
  animation-direction: normal;
  animation-iteration-count: infinite;
  animation-timing-function: normal;
}

.squish.right {
  margin: 0pt;
  margin-left: 25pt;
  margin-right: -15pt;
}


.digit.left {animation-duration: 7.31415926535s}
.digit.center {animation-duration: 6.180339887s}
.digit.right {animation-duration: 8s}

@keyframes bounce {
  from {transform: translateY(0pt)}
  10% {transform: translateY(50pt)}
  20% {transform: translateY(75pt)}
  30% {transform: translateY(87.5pt)}
  5%, 15%, 25%, 35%, 90% {transform: translateY(100pt)}
}

.squish.left {animation-duration: 7.31415926535s}
.squish.center {animation-duration: 6.180339887s}
.squish.right {animation-duration: 8s}

@keyframes squish {
  from, 5% {transform: scale(0%) translateY(-400%); background-color: transparent}
  6%, 11%, 13% {transform: scale(50%)  translateY(-50%); background-color: var(--bs-body-color)}
  21%, 23% {transform: scale(75%)  translateY(-25%)}
  31%, 33% {transform: scale(90%)  translateY(-10%)}
  41%, 43% {transform: scale(100%)}
  99% {transform: translateY(1000%)}
  99.9% {transform: translateY(1000%) scale(0%)}
  to {transform: scale(0%) translateY(-400%); display: none}
}
</style>

