project:
  type: website

website:
  title: "0SK42"
  description: "OSK42 - blog de Maths et d'Informatique"
  site-url: https://osk42.quarto.pub
  image: "_images/OsKaR.png"
  navbar:
    left:

      - text: "A propos"
        href: about.qmd


      - text: Sujets
        menu:
          - text: Mathématiques
            href: posts/maths/>>mathematiques.md
          - text: Informatique
            href: posts/informatique/>>informatique.qmd
          - text: Philosophie
            href: posts/philosophie/>>philosophie.qmd
          - text: Réflexions
            href: posts/>>reflexions.qmd

    right:
      - icon: person-vcard
        text: CV
        href: CV.qmd

      - icon: share
        menu:
          - icon: github
            text: github
            href: https://github.com/OsKaR31415
          - icon: youtube
            text: youtube
            href: https://youtube.com/@oskar31415
          - icon: envelope
            text: email
            href: mailto:oscar.plaisant@orange.fr
          - icon: rss
            href: index.xml
            text: flux RSS du blog
      - icon: rss
        href: index.xml

  twitter-card:
    image: "https://osk42.quarto.pub/_images/OsKaR.png"
  open-graph:
    image: "https://osk42.quarto.pub/_images/OsKaR.png"

  comments:
    giscus:
      repo: OsKaR31415/blog
      repo-id: "R_kgDOItLnjQ"
      category: "Announcements"
      category-id: "DIC_kwDOItLnjc4CYln7"
      mapping: "url"
      reactions-enabled: true
      loading: "lazy"
      input-position: "bottom"
      theme:
        dark: "noborder_dark"
        light: "noborder_light"
      language: "fr"


format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    include-in-header:
      text: |
        <script data-goatcounter="https://osk42.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
    link-external-icon: true # show an icon after every external link

execute:
  freeze: auto

editor:
  render-on-save: false

