project:
  type: website

website:
  title: "0SK42"
  description: "0SK42"
  site-url: https://osk42.quarto.pub
  navbar:
    right:
      - posts/maths/>>mathematiques.md
      - posts/informatique/>>informatique.qmd
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/OsKaR31415
      - icon: youtube
        href: https://youtube.com/@oskar31415
format:
  html:
    theme: superhero
    css: styles.css

editor:
  render-on-save: false

