project:
  type: website

website:
  title: "0SK42"
  description: "OSK42 - blog de Maths et d'Informatique"
  site-url: https://osk42.quarto.pub
  image: "_images/OsKaR.png"
  navbar:
    left:
      - text: Sujets
        menu:
          - text: Mathématiques
            href: posts/maths/>>mathematiques.md
          - text: Informatique
            href: posts/informatique/>>informatique.qmd
          - text: Réflexions
            href: posts/>>reflexions.qmd

      - icon: share
        menu:
        - icon: github
          text: github
          href: https://github.com/OsKaR31415
        - icon: youtube
          text: youtube
          href: https://youtube.com/@oskar31415
        - icon: envelope
          text: email
          href: mailto:oscar.plaisant@orange.fr

      - icon: person-vcard
        text: CV
        href: CV.qmd
      - text: "A propos"
        href: about.qmd

  twitter-card:
    image: "https://osk42.quarto.pub/_images/OsKaR.png"
  open-graph:
    image: "https://osk42.quarto.pub/_images/OsKaR.png"


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    include-in-header:
      text: |
        <script data-goatcounter="https://osk42.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
    link-external-icon: true # show an icon after every external link


editor:
  render-on-save: false

