---
title: Ma mémoire
date: 2025-04-09
author: Oscar Plaisant
categories: poesie
---

Quelquefois, le soir, dans le tram, sous la lumière blanche qui s'attache aux couleurs insomniaques, le vent siffle soufflant un son sérieux d'introspection; et le trop plein d'air me ramène ma mémoire.

Mémoire mordue d'un amour murmuré. <br/>
Le décor romantique du tram, ses murs verts et myrtille, ravivent le souvenir de cette ravissante soirée et ramène ma mémoire.

Mémoire d'un amour de mars qu'un vent d'avril à vu revivre en vain. <br/>
Voie lactée, tes yeux sont ceux des amoureux perdus et je rame sans répit pour suivre ton cours gris d'argent, comme le tram brillant dont les reflets saillants ramènent ma mémoire.

Mémoire remplie de souvenirs tranchants. <br/>
La lame du temps, de son fil bleu, élague l'espoir. <br/>
Et puis les pleurs, la pluie de l'âme dont les flaques luisent sur le sol pâle. <br/>
Et les reflets ruisselant sur les rails, glissant sans répit pour mon cœur vers l'arrêt suivant. <br/>
Les portes coulissantes laissent rentrer une poignée d'air morose, une bouffée de personnes froides. <br/>
Les secousses caressent mon corps et ramènent ma mémoire.

Mémoire corrompue des instants que l'on voudrait garder, mais qui ne sont plus. <br/>
Leur image rémanante torture mon esprit et ramène ma mémoire.


Mémoire remplie de regrets et d'instants heureux morts.

. . .

Puis l'amour pars un jour écrasé par le tram.
<br/>
Il suffit que plus rien ne ramène ma mémoire.
<br/>
Mémoire ...


Quand l'amour meurt, c'est l'oubli qui le tue.

