---
title: Sur les divers avantages de groupes de lecture pour la philosophie
description:
categories: philosophie
date: 2025-09-15
---

# Contexte

Nous savons combient il peut être difficile de lire (même un texte court) un livre de philosophie, surtout s'il fait partie de ces textes *difficiles*, qui ne vous tiennent pas par la main, mais qui au contrairent sont obscurs, *obfusqués*.

Ces lectures sont difficiles d'abord car la lecture *en général* est difficile. Il faut, pour pouvoir lire, trouver du temps et de la motivation. Il faut également réussir à entrer dans un état d'esprit compatible à la lecture.

Ensuite, en philosophie, la compréhension est un obstacle difficile à surmonter.

# Les lectures collectives

J'ai récemment commencer à "organiser" (plutôt proposer) des lectures de textes de philosophie, dans un groupe discord de philosophie ([le serveur discord de MrPhi](discord.gg/8Wa6dcnSFx) pour le nommer).

Les choses se passent ainsi : un texte est choisi (parmi ceux que je propose, car il faut que je possède le livre : je préfère lire sur papier) par les personnes présentes. Je lis alors le texte à voix haute. Régulièrement, la lecture est interrompue par des remarques qui font tout l'intérêt de ces lectures.

## Un autre rapport à la lecture

Le fait de lire publiquement un texte donne une certaine motivation à lire, et entraine également à articulier et à moins bégayer (ce que j'ai tendance à faire) (sans parler de ma tendance à remplacer certains mots quand j'en un autre qui marche aussi).

Plus encore, le fait de donner un rendez-vous à d'autres personnes, de s'engager et de savoir qu'on a libéré une soirée à cet effet, tout cela règle le problème de la motivation à lire (certes, en le déplaçant vers celui de la motivation à organiser l'événement, qui s'avère être moins un problème pour moi).

## Les remarques et discussions

Ce sont les discussions qui ont lieu entre les moment de lecture qui apportent encore plus d'intérêt à ces lectures.

 