---
title: Sur le désir, le manque et le frustration amoureuse
description: reflexions sur la sensation causée par l'absence d'une personne aimée
categories: philosophie
date: 2025-08-03
---
# Introduction : contexte

Je voudrais ici parler de la sensation que l'on ressent lorsque l'on est éloigné par la force des circonstances d'une personne que l'on aime (avec en tête principalement des relations romantiques, même si j'ai la conviction que ce qui est dit ensuite peut se dire également des relations amicales). Par "éloignement" j'entends un éloignement physique et relationnel ; plus généralement des circonstances qui rendent plus rares les interactions (physiques ou non). Il me semble simplement que les constatations faites plus loin s'appliquent surtout à l'affection romantique ou amicale, et moins à l'attirance purement physique, bien qu'on y puisse trouver des sentiments similaires.

# Premières intuitions

Pour penser cette situation, la compréhension du désir amoureux est centrale. Une première approche consiste à assimiler cette sensation à un manque : le désir en question ne serait que la conséquence de ce que la personne aimée manque à notre entourage.

Cette manière de penser le désir — et en particulier le désir amoureux — est assez commune. On dit d'ailleurs qu'une personne "nous manque" et on penserait presque que, lorsqu'une personne aimée n'est pas là, "il nous manque une partie de nous-même". 


# Une meilleure conception du désir

## Problèmes du désir comme manque

Penser le désir comme un manque pose plusieurs problèmes philosophiques. D'abord, cette approche implique que s'il n'y a plus de manque, il n'y a plus de désir, autrement dit, elle affirme que l'on ne peut pas désirer ce qu'on a déjà. Ainsi, voir le désir comme un manque semble contradictoire, car on peut désirer une personne même si elle est déjà à côté de nous. Cette grille de lecture fonctionne très bien pour le désir de consommer (au sens de la société de consommation, et au sens de consommer des aliments), puisque le désir de posséder un objet disparait largement une fois que cet objet devient commun par habitude.

## Le désir comme mouvement

Une conception plus adéquate du désir serait de voir le désir comme un mouvement. Désirer une chose, c'est faire un mouvement vers cette chose, qu'il soit physique — corporel — ou bien mental — avoir une pensée pour, une pensée vers cette chose. Cette manière de penser le désir parais mieux rendre compte du désir amoureux, en effet, on peut désirer la personne aimée même si elle est déjà auprès de nous, et on comprend également ces pensées que cause l'amour, et qui sont des pensées qui rapprochent mentalement de la personne aimée, qui font des "mouvements intellectuels" vers la personne aimée.

On peut appliquer cette idée pour d'autres types de désirs, comme le désir de posséder un objet. Désirer un objet, c'est faire un mouvement vers cet objet : soit le mouvement de l'acheter, soit le mouvement de l'utiliser, soit simplement le mouvement intellectuel de s'imaginer l'utiliser, de s'imaginer la joie qu'il procurerait. Cela fait apparaître assez naturellement la notion de frustration : lorsqu'un désir (un mouvement) est contrarié (empêché), il suit une tristesse que l'on appelle frustration. On est frustré de ne pas pouvoir acheter ou utiliser un objet. Serait-il alors pertinent de recatégoriser le "manque amoureux" comme une frustration ?

## La frustration plutôt que le manque

Une fois admise cette approche du désir comme un mouvement concret, il semble en effet logique de penser que cette sensation lorsque la personne aimée est absente n'est pas tant un manque qu'une frustration. C'est tout le but de cet article d'en arriver à une telle recatégorisation qui m'apparaît plus adéquate — j'ai déjà fait apparaitre les problèmes de la conception du désir comme manque.

Ainsi, je crois qu'une caractérisation correcte du manque amoureux passe plutôt par l'idée de frustration que l'idée de manque. De mon point de vie subjectif, cette description correspond mieux au sentiment en plus d'être une description plus correcte philosophiquement. 

On pourrait également argumenter qu'une relation suffisamment sécurisée ne crée pas de tristesse, de peur ou de douleur lorsque l'on est séparés. Je ne partage pas ce point de vue, d'abord à cause de ma conception du désir — explicitée plus haut — mais également par des expériences de vie qui m'amènent à croire que ce sentiment de frustration par l'absence peut exister même dans une relation sécurisée (et je pense pouvoir notamment tenir pour preuve certaines relations amicales, qui bien que sécurisées, peuvent nous attrister dans l'éloignement).



