---
title: "Aphorismes et textes courts — hiver 2025"
date: 2025-10
categories: [ aphorisme, réflexion ]
---

Je ne sais pas parler comme je ressens.

<hr/>

Les jeunes enfants me regardent souvent avec une intensité rare pour leur âge. Est-ce parce que je les regarde comme des adultes ?

<hr/>


On pourrait croire que les paysages qui défilent derrière les vitres d'un train ont cette poésie que les films leur donne.
On voudrait qu'ils aient cette intensité presque dramatique.
En réalité ils ont quelque chose de banal et décevant.
Bien sûr, on peut apprécier les regarder, mais il leur manque quelque chose — peut-être une musique de fond ou une pertinence narrative.<br/>
Les paysages de nuit sont plus étonnants encore.
On aurait envie qu'ils nous montrent des villes illuminées, au loin&nbsp;; mais ils ne sont qu'un enchaînement d'arbres et de poteaux entrecoupé de quais de gares. L'illumination n'est pas celle d'un coucher de soleil ou d'un soir de pleine lune, mais celle d'un mur éclairé à la lampe-torche, qui ne laisse voir que des détails inélégants.

<hr/>

L'ennui nourrit l'ardeur.

<hr/>

Cette rage fatiguée qui nous prends au milieu de la routine. La fatigue nous fait vivre comme dans un songe : dans une dispute sous fatigue, on se voit alors comme en rêve avoir une colère intense, avec cette sorte d'exaspération : on presque autant énervé d'être énervé qu'on l'est contre ce qui nous énerve. Peut-être est-ce en réalité toujours le cas, et le demi-rêve de la fatigue nous le fait-il seulement voir plus clairement.

<hr/>

"intensité", "intense", quels beaux mots. Pas beaux seulement pour leurs sons (quoique "j'aime d'intenses vertiges" sonne très bien), mais pour la promesse qu'ils font : on ne peut pas dire "c'est intense" sans révéler une certaine émotion. Les meilleurs moments, les plus importants, sont ceux que l'on vit avec intensité. L'intense sous-tend toujours une certaine beauté.

<hr/>

Quel plaisir, le soir, d'enlever sa chemise pour trouver qu'en dessous on a encore un T-shirt.

<hr/>

Celui qui se prends pour ton maitre, te prends-il pour son chien ?

<hr/>


